---
title: "Objective Function Estimation"
output: pdf_document
---

```{r Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("readxl")
library("msm")
library("stargazer")
library("lmtest")
library("sandwich")
library("estimatr")
library("texreg")
library("lattice")
library("visreg")
data <- read_excel("Compiled Data.xlsx")

#Forecast months only
#data <- filter(data, fc_mth == 1)

#GFC Dummy
data$Dates <- as.Date(as.character(data$Dates), "%Y-%m-%d") # correct date format
data$Dates <- format(data$Dates, "%Y-%m-%d") # change to Date variable
data$pre_gfc <- ifelse(data$Dates <="2007/01/01", 1, 0)
data$post_gfc <- ifelse(data$Dates >="2009/01/01", 1, 0)
data$gfc <- ifelse(data$pre_gfc == 0 & data$post_gfc ==0, 1, 0)
post_2012 <- ifelse(data$Dates < "2012/01/01", 0 , 1)
post_2013 <- ifelse(data$Dates < "2013/01/01", 0 , 1)
# Accounting for increasing or decreasing path of forecasts
inc_ur_1 <- ifelse(data$fcurq1 >= data$fcurq0,1, 0 )
inc_gdp_1 <- ifelse(data$fcgdpq1 >= data$fcgdpq0,1, 0 )
inc_ur_2 <- ifelse(data$fcurq2 >= data$fcurq0,1, 0 )
inc_gdp_2 <- ifelse(data$fcgdpq2 >= data$fcgdpq0,1, 0 )
inc_ur_3 <- ifelse(data$fcurq3 >= data$fcurq0,1, 0 )
inc_gdp_3 <- ifelse(data$fcgdpq3 >= data$fcgdpq0,1, 0 )
inc_ur_4 <- ifelse(data$fcurq4 >= data$fcurq0,1, 0 )
inc_gdp_4 <- ifelse(data$fcgdpq4 >= data$fcgdpq0,1, 0 )
inc_ur_5 <- ifelse(data$fcurq5 >= data$fcurq0,1, 0 )
inc_gdp_5 <- ifelse(data$fcgdpq5 >= data$fcgdpq0,1, 0 )
inc_ur_6 <- ifelse(data$fcurq6 >= data$fcurq0,1, 0 )
inc_gdp_6 <- ifelse(data$fcgdpq6 >= data$fcgdpq0,1, 0 )

dec_ur_1 <- ifelse(inc_ur_1 == 0 ,1, 0 )
dec_gdp_1 <- ifelse(inc_gdp_1 == 0 ,1, 0 )
dec_ur_2 <- ifelse(inc_ur_2 == 0 ,1, 0 )
dec_gdp_2 <- ifelse(inc_gdp_2 == 0 ,1, 0 )
dec_ur_3 <- ifelse(inc_ur_3 == 0 ,1, 0 )
dec_gdp_3 <- ifelse(inc_gdp_3 == 0 ,1, 0 )
dec_ur_4 <- ifelse(inc_ur_4 == 0 ,1, 0 )
dec_gdp_4 <- ifelse(inc_gdp_4 == 0 ,1, 0 )
dec_ur_5 <- ifelse(inc_ur_5 == 0 ,1, 0 )
dec_gdp_5 <- ifelse(inc_gdp_5 == 0 ,1, 0 )
dec_ur_6 <- ifelse(inc_ur_6 == 0 ,1, 0 )
dec_gdp_6 <- ifelse(inc_gdp_6 == 0 ,1, 0 )
```

```{r Defining variables for full dataset}
# Y variables
netneg <- data$`Net negativity score`
neg <- data$`Percentage negative`
pos <- data$`Percentage positive`
netnegur <- data$`Net negativity score with unemploy`
percentpositive <- data$`Percentage positive`
percentnegative <- data$`Percentage negative`
#Inflation
inf_f_0 <- data$fccpiiq0
inf_f_1 <- data$fccpiiq1
inf_f_2 <- data$fccpiiq2
inf_f_3 <- data$fccpiiq3
inf_f_4 <- data$fccpiiq4
inf_f_5 <- data$fccpiiq5
inf_f_6 <- data$fccpiiq6

inf_f_dataframe <- data.frame(inf_f_1, inf_f_2, inf_f_3, inf_f_4, inf_f_5, inf_f_6)

inf_f_0sq <- inf_f_0^2
inf_f_1sq <- inf_f_1^2
inf_f_2sq <- inf_f_2^2
inf_f_3sq <- inf_f_3^2
inf_f_4sq <- inf_f_4^2
inf_f_5sq <- inf_f_5^2
inf_f_6sq <- inf_f_6^2

inf_fsq_dataframe <- data.frame(inf_f_1sq, inf_f_2sq, inf_f_3sq, inf_f_4sq, inf_f_5sq, inf_f_6sq)

#Inflation averages
inf_f_01 <- (inf_f_0+inf_f_1)/2
inf_f_02 <- (inf_f_0+inf_f_1 + inf_f_2)/3
inf_f_03 <- (inf_f_0+inf_f_1 + inf_f_2 + inf_f_3)/4
inf_f_04 <- (inf_f_0+inf_f_1 + inf_f_2 + inf_f_3+inf_f_4)/5
inf_f_05 <- (inf_f_0+inf_f_1 + inf_f_2 + inf_f_3+inf_f_4 + inf_f_5)/6
inf_f_06 <- (inf_f_0+inf_f_1 + inf_f_2 + inf_f_3+inf_f_4 + inf_f_5 + inf_f_6)/7

inf_f_x_dataframe <- data.frame(inf_f_01, inf_f_02, inf_f_03, inf_f_04, inf_f_05, inf_f_06)

inf_f_01sq <- inf_f_01^2
inf_f_02sq <- inf_f_02^2
inf_f_03sq <- inf_f_03^2
inf_f_04sq <- inf_f_04^2
inf_f_05sq <- inf_f_05^2
inf_f_06sq <- inf_f_06^2

inf_f_xsq_dataframe <- data.frame(inf_f_01sq, inf_f_02sq, inf_f_03sq, inf_f_04sq, inf_f_05sq, inf_f_06sq)

#GDP growth
gdp_f_0 <- data$fcgdpq0
gdp_f_1 <- data$fcgdpq1
gdp_f_2 <- data$fcgdpq2
gdp_f_3 <- data$fcgdpq3
gdp_f_4 <- data$fcgdpq4
gdp_f_5 <- data$fcgdpq5
gdp_f_6 <- data$fcgdpq6

gdp_f_dataframe <- data.frame(gdp_f_1, gdp_f_2, gdp_f_3, gdp_f_4, gdp_f_5, gdp_f_6)

gdp_f_0sq <- gdp_f_0^2
gdp_f_1sq <- gdp_f_1^2
gdp_f_2sq <- gdp_f_2^2
gdp_f_3sq <- gdp_f_3^2
gdp_f_4sq <- gdp_f_4^2
gdp_f_5sq <- gdp_f_5^2
gdp_f_6sq <- gdp_f_6^2

gdp_fsq_dataframe <- data.frame(gdp_f_1sq, gdp_f_2sq, gdp_f_3sq, gdp_f_4sq, gdp_f_5sq, gdp_f_6sq)

#GDP growth averages
gdp_f_01 <- (gdp_f_0+gdp_f_1)/2
gdp_f_02 <- (gdp_f_0+gdp_f_1 + gdp_f_2)/3
gdp_f_03 <- (gdp_f_0+gdp_f_1 + gdp_f_2 + gdp_f_3)/4
gdp_f_04 <- (gdp_f_0+gdp_f_1 + gdp_f_2 + gdp_f_3+gdp_f_4)/5
gdp_f_05 <- (gdp_f_0+gdp_f_1 + gdp_f_2 + gdp_f_3+gdp_f_4 + gdp_f_5)/6
gdp_f_06 <- (gdp_f_0+gdp_f_1 + gdp_f_2 + gdp_f_3+gdp_f_4 + gdp_f_5 + gdp_f_6)/7

gdp_f_x_dataframe <- data.frame(gdp_f_01, gdp_f_02, gdp_f_03, gdp_f_04, gdp_f_05, gdp_f_06)

gdp_f_01_inc <- gdp_f_01 * inc_gdp_1
gdp_f_02_inc <- gdp_f_02 * inc_gdp_2
gdp_f_03_inc <- gdp_f_03 * inc_gdp_3
gdp_f_04_inc <- gdp_f_04 * inc_gdp_4
gdp_f_05_inc <- gdp_f_05 * inc_gdp_5
gdp_f_06_inc <- gdp_f_06 * inc_gdp_6

gdp_f_xinc_dataframe <- data.frame(gdp_f_01_inc, gdp_f_02_inc, gdp_f_03_inc, gdp_f_04_inc, gdp_f_05_inc, gdp_f_06_inc)

gdp_f_01_dec <- gdp_f_01 * dec_gdp_1
gdp_f_02_dec <- gdp_f_02 * dec_gdp_2
gdp_f_03_dec <- gdp_f_03 * dec_gdp_3
gdp_f_04_dec <- gdp_f_04 * dec_gdp_4
gdp_f_05_dec <- gdp_f_05 * dec_gdp_5
gdp_f_06_dec <- gdp_f_06 * dec_gdp_6

gdp_f_xdec_dataframe <- data.frame(gdp_f_01_dec, gdp_f_02_dec, gdp_f_03_dec, gdp_f_04_dec, gdp_f_05_dec, gdp_f_06_dec)

gdp_f_01sq <- gdp_f_01^2
gdp_f_02sq <- gdp_f_02^2
gdp_f_03sq <- gdp_f_03^2
gdp_f_04sq <- gdp_f_04^2
gdp_f_05sq <- gdp_f_05^2
gdp_f_06sq <- gdp_f_06^2

gdp_f_xsq_dataframe <- data.frame(gdp_f_01sq, gdp_f_02sq, gdp_f_03sq, gdp_f_04sq, gdp_f_05sq, gdp_f_06sq)

#Unemployment
ur_f_0 <- data$fcurq0
ur_f_1 <- data$fcurq1
ur_f_2 <- data$fcurq2
ur_f_3 <- data$fcurq3
ur_f_4 <- data$fcurq4
ur_f_5 <- data$fcurq5
ur_f_6 <- data$fcurq6

ur_f_dataframe <- data.frame(ur_f_1, ur_f_2, ur_f_3, ur_f_4, ur_f_5, ur_f_6)

ur_f_0sq <- ur_f_0^2
ur_f_1sq <- ur_f_1^2
ur_f_2sq <- ur_f_2^2
ur_f_3sq <- ur_f_3^2
ur_f_4sq <- ur_f_4^2
ur_f_5sq <- ur_f_5^2
ur_f_6sq <- ur_f_6^2

ur_fsq_dataframe <- data.frame(ur_f_1sq, ur_f_2sq, ur_f_3sq, ur_f_4sq, ur_f_5sq, ur_f_6sq)

#Unemployment averages
ur_f_01 <- (ur_f_0+ur_f_1)/2
ur_f_02 <- (ur_f_0+ur_f_1 + ur_f_2)/3
ur_f_03 <- (ur_f_0+ur_f_1 + ur_f_2 + ur_f_3)/4
ur_f_04 <- (ur_f_0+ur_f_1 + ur_f_2 + ur_f_3+ur_f_4)/5
ur_f_05 <- (ur_f_0+ur_f_1 + ur_f_2 + ur_f_3+ur_f_4+ur_f_5)/6
ur_f_06 <- (ur_f_0+ur_f_1 + ur_f_2 + ur_f_3+ur_f_4+ur_f_5+ur_f_6)/7

ur_f_x_dataframe <- data.frame(ur_f_01, ur_f_02, ur_f_03, ur_f_04, ur_f_05, ur_f_06)

ur_f_01_inc <- ur_f_01 * inc_ur_1
ur_f_02_inc <- ur_f_02 * inc_ur_2
ur_f_03_inc <- ur_f_03 * inc_ur_3
ur_f_04_inc <- ur_f_04 * inc_ur_4
ur_f_05_inc <- ur_f_05 * inc_ur_5
ur_f_06_inc <- ur_f_06 * inc_ur_6

ur_f_xinc_dataframe <- data.frame(ur_f_01_inc, ur_f_02_inc, ur_f_03_inc, ur_f_04_inc, ur_f_05_inc, ur_f_06_inc)

ur_f_01_dec <- ur_f_01 * dec_ur_1
ur_f_02_dec <- ur_f_02 * dec_ur_2
ur_f_03_dec <- ur_f_03 * dec_ur_3
ur_f_04_dec <- ur_f_04 * dec_ur_4
ur_f_05_dec <- ur_f_05 * dec_ur_5
ur_f_06_dec <- ur_f_06 * dec_ur_6

ur_f_xdec_dataframe <- data.frame(ur_f_01_dec, ur_f_02_dec, ur_f_03_dec, ur_f_04_dec, ur_f_05_dec, ur_f_06_dec)

ur_f_01sq <- ur_f_01^2
ur_f_02sq <- ur_f_02^2
ur_f_03sq <- ur_f_03^2
ur_f_04sq <- ur_f_04^2
ur_f_05sq <- ur_f_05^2
ur_f_06sq <- ur_f_06^2

ur_f_xsq_dataframe <- data.frame(ur_f_01sq, ur_f_02sq, ur_f_03sq, ur_f_04sq, ur_f_05sq, ur_f_06sq)

# Unemployment gap
urg_f_0 <- ur_f_0 - 4.5
urg_f_1 <- ur_f_1 - 4.5
urg_f_2 <- ur_f_2 - 4.5
urg_f_3 <- ur_f_3 - 4.5
urg_f_4 <- ur_f_4 - 4.5
urg_f_5 <- ur_f_5 - 4.5
urg_f_6 <- ur_f_6 - 4.5

#Unemployment gap averages
urg_f_01 <- (urg_f_0+urg_f_1)/2
urg_f_02 <- (urg_f_0+urg_f_1 + urg_f_2)/3
urg_f_03 <- (urg_f_0+urg_f_1 + urg_f_2 + urg_f_3)/4
urg_f_04 <- (urg_f_0+urg_f_1 + urg_f_2 + urg_f_3+urg_f_4)/5
urg_f_05 <- (urg_f_0+urg_f_1 + urg_f_2 + urg_f_3+urg_f_4+urg_f_5)/6
urg_f_06 <- (urg_f_0+urg_f_1 + urg_f_2 + urg_f_3+urg_f_4+urg_f_5+urg_f_6)/7

urg_f_x_dataframe <- data.frame(urg_f_01, urg_f_02, urg_f_03, urg_f_04, urg_f_05, urg_f_06)

urg_f_01sq <- urg_f_01^2
urg_f_02sq <- urg_f_02^2
urg_f_03sq <- urg_f_03^2
urg_f_04sq <- urg_f_04^2
urg_f_05sq <- urg_f_05^2
urg_f_06sq <- urg_f_06^2

urg_f_xsq_dataframe <- data.frame(urg_f_01sq, urg_f_02sq, urg_f_03sq, urg_f_04sq, urg_f_05sq, urg_f_06sq)
#Dummy variable for governor
phillowe <- data$`Phillip Lowe`

#Australian uncertainty index (Caggiano)
uncertainty <- data$Australia

#Global uncertainty (VIX)
vix <- data$us_vix

#Commodity price index
commpi <- data$commpi
commpi_inf_q1 <- data$`Quarterly inflation for commpi`
commpi_inf_q4 <- data$`Year-ended inflation for commpi`

#US Fed Funds Rate
us_ffr <- data$us_ffr

#Nominal Trade Weighted Index
ntwi <- data$ntwi
ntwiqg <- data$`Quarterly % change in ntwi`
ntwiyeg <- data$`4 Quarter % change in NTWi`

#Australian BBB corp bond yield relative to 10-year AGS constant maturity. 
aus_bbb <- data$sprd_ir_cbb_gb10

# Moody’s seasoned BAA corporate bond yield relative to yield on 10-year Treasury constant maturity, obtained from FRED; end of month value

us_baa <- data$sprd_ir_us_cbb_gb10

# Money market spread between 3-month bank-accepted bill (BAB) rate and 3-month Australian dollar overnight indexed swap (OIS) rate (3-month zero-coupon forward rate prior to July 2001); end of month value
aus_bab <- data$sprd_ir_bab_ois3

# Credit market spread between average large business variable lending rate and 3-month BAB rate; end of month value

business_bab <- data$sprd_ir_lbiz_bab3

#House price variables
rppi <- data$`RPPI (lagged)`
rppiqg <- data$`RPPIQG (lagged)`
rppiyeg <- data$`RPPIYEG (lagged)`

ehpi <- data$`EHPI (lagged)`
ehpiqg <- data$`EHPIQG (lagged)`
ehpiyeg <- data$`EHPIYEG (lagged)`

adpy <- data$`ADP (lagged)`
adpyqg <- data$`ADPYQG (lagged)`
adpyeg <- data$`ADPYEG (lagged)`

# Wage growth variables
wpi <- data$`WPI (3 month Lag)`

wpiyeg <-data$`WPIYEG ( 3 month lag)`
wpiqg <- data$`WPIQG (3 month lag)`

wpiyeg_phillowe <- wpiyeg * phillowe
wpiqg_phillowe <- wpiqg * phillowe
```

```{r Defining variables for subset of forecast months only}
# Y variables
netneg_fcmth <- data_fcmth$`Net negativity score`
netnegur_fcmth <- data_fcmth$`Number of negative words including unemploy`

#Inflation
inf_f_0_fcmth <- data_fcmth$fccpiiq0
inf_f_1_fcmth <- data_fcmth$fccpiiq1
inf_f_2_fcmth <- data_fcmth$fccpiiq2
inf_f_3_fcmth <- data_fcmth$fccpiiq3
inf_f_4_fcmth <- data_fcmth$fccpiiq4

inf_f_0sq_fcmth <- inf_f_0_fcmth^2
inf_f_1sq_fcmth <- inf_f_1_fcmth^2
inf_f_2sq_fcmth <- inf_f_2_fcmth^2
inf_f_3sq_fcmth <- inf_f_3_fcmth^2
inf_f_4sq_fcmth <- inf_f_4_fcmth^2

#Inflation averages
inf_f_01_fcmth <- (inf_f_0_fcmth+inf_f_1_fcmth)/2
inf_f_02_fcmth <- (inf_f_0_fcmth+inf_f_1_fcmth + inf_f_2_fcmth)/3
inf_f_03_fcmth <- (inf_f_0_fcmth+inf_f_1_fcmth + inf_f_2_fcmth + inf_f_3_fcmth)/4
inf_f_04_fcmth <- (inf_f_0_fcmth+inf_f_1_fcmth + inf_f_2_fcmth + inf_f_3_fcmth+inf_f_4_fcmth)/5

inf_f_x_dataframe_fcmth <- data.frame(inf_f_01_fcmth, inf_f_02_fcmth, inf_f_03_fcmth, inf_f_04_fcmth)

inf_f_01sq_fcmth <- inf_f_01_fcmth^2
inf_f_02sq_fcmth <- inf_f_02_fcmth^2
inf_f_03sq_fcmth <- inf_f_03_fcmth^2
inf_f_04sq_fcmth <- inf_f_04_fcmth^2

inf_f_xsq_dataframe_fcmth <- data.frame(inf_f_01sq_fcmth, inf_f_02sq_fcmth, inf_f_03sq_fcmth, inf_f_04sq_fcmth)

#GDP growth
gdp_f_0_fcmth <- data_fcmth$fcgdpq0
gdp_f_1_fcmth <- data_fcmth$fcgdpq1
gdp_f_2_fcmth <- data_fcmth$fcgdpq2
gdp_f_3_fcmth <- data_fcmth$fcgdpq3
gdp_f_4_fcmth <- data_fcmth$fcgdpq4

gdp_f_0sq_fcmth <- gdp_f_0_fcmth^2
gdp_f_1sq_fcmth <- gdp_f_1_fcmth^2
gdp_f_2sq_fcmth <- gdp_f_2_fcmth^2
gdp_f_3sq_fcmth <- gdp_f_3_fcmth^2
gdp_f_4sq_fcmth <- gdp_f_4_fcmth^2

#GDP growth averages
gdp_f_01_fcmth <- (gdp_f_0_fcmth+gdp_f_1_fcmth)/2
gdp_f_02_fcmth <- (gdp_f_0_fcmth+gdp_f_1_fcmth + gdp_f_2_fcmth)/3
gdp_f_03_fcmth <- (gdp_f_0_fcmth+gdp_f_1_fcmth + gdp_f_2_fcmth + gdp_f_3_fcmth)/4
gdp_f_04_fcmth <- (gdp_f_0_fcmth+gdp_f_1_fcmth + gdp_f_2_fcmth + gdp_f_3_fcmth+gdp_f_4_fcmth)/5

gdp_f_x_dataframe_fcmth <- data.frame(gdp_f_01_fcmth, gdp_f_02_fcmth, gdp_f_03_fcmth, gdp_f_04_fcmth)

gdp_f_01sq_fcmth <- gdp_f_01_fcmth^2
gdp_f_02sq_fcmth <- gdp_f_02_fcmth^2
gdp_f_03sq_fcmth <- gdp_f_03_fcmth^2
gdp_f_04sq_fcmth <- gdp_f_04_fcmth^2

gdp_f_xsq_dataframe_fcmth <- data.frame(gdp_f_01sq_fcmth, gdp_f_02sq_fcmth, gdp_f_03sq_fcmth, gdp_f_04sq_fcmth)

#Unemployment
ur_f_0_fcmth <- data_fcmth$fcurq0
ur_f_1_fcmth <- data_fcmth$fcurq1
ur_f_2_fcmth <- data_fcmth$fcurq2
ur_f_3_fcmth <- data_fcmth$fcurq3
ur_f_4_fcmth <- data_fcmth$fcurq4

ur_f_0sq_fcmth <- ur_f_0_fcmth^2
ur_f_1sq_fcmth <- ur_f_1_fcmth^2
ur_f_2sq_fcmth <- ur_f_2_fcmth^2
ur_f_3sq_fcmth <- ur_f_3_fcmth^2
ur_f_4sq_fcmth <- ur_f_4_fcmth^2

#Unemployment averages
ur_f_01_fcmth <- (ur_f_0_fcmth+ur_f_1_fcmth)/2
ur_f_02_fcmth <- (ur_f_0_fcmth+ur_f_1_fcmth + ur_f_2_fcmth)/3
ur_f_03_fcmth <- (ur_f_0_fcmth+ur_f_1_fcmth + ur_f_2_fcmth + ur_f_3_fcmth)/4
ur_f_04_fcmth <- (ur_f_0_fcmth+ur_f_1_fcmth + ur_f_2_fcmth + ur_f_3_fcmth+ur_f_4_fcmth)/5

ur_f_x_dataframe_fcmth <- data.frame(ur_f_01_fcmth, ur_f_02_fcmth, ur_f_03_fcmth, ur_f_04_fcmth)

ur_f_01sq_fcmth <- ur_f_01_fcmth^2
ur_f_02sq_fcmth <- ur_f_02_fcmth^2
ur_f_03sq_fcmth <- ur_f_03_fcmth^2
ur_f_04sq_fcmth <- ur_f_04_fcmth^2

ur_f_xsq_dataframe_fcmth <- data.frame(ur_f_01sq_fcmth, ur_f_02sq_fcmth, ur_f_03sq_fcmth, ur_f_04sq_fcmth)

# Dummy variable for governor
phillowe_fcmth <- data_fcmth$`Phillip Lowe`

#Uncertainty
uncertainty_fcmth <- data_fcmth$Australia
```

```{r Baseline regression with inflation only}

# Loop over different forecast horizon averages
n <- 6

lr_inf_infsq <- lapply(1:n,function(x) lm_robust(netnegur ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] +phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq, summary)
#lapply(summaries, function(x) x$coefficients[, c(1,4)])
print(lapply(lr_inf_infsq, function(x) coef(summary(x))[,1:4]), digits = 5)
print(sapply(summaries, function(x) c(r_sq = x$r.squared, 
                                adj_r_sq = x$adj.r.squared)), digits = 3)
print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
print(lapply(lr_inf_infsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 4)

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and a fixed effects for governor

model_inf_02 <- lm(netneg ~ inf_f_02+ I(inf_f_02^2) + phillowe)
#lmtest::coeftest(model_inf_01, vcov. = sandwich::vcovHC(model_inf_01, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_01_est <- -coef(model_inf_01)[2]/(2*coef(model_inf_01)[3])
#model_inf_01_est


## Delta method standard error and CFI

#model_inf_01_est_se <- deltamethod(~-x2/(2*x3),coef(model_inf_01),vcovHC(model_inf_01, type = 'HC1'))
#print(model_inf_01_est_se)

#n <- 141
#error <- qt(0.975,df = n-1)*model_inf_01_est_se /sqrt(n)
#print(error) 
#left_cfi <- model_inf_01_est - error
#right_cfi <- model_inf_01_est + error
#print(left_cfi)
#print(right_cfi)
```

```{r Baseline regression with inflation only - Forecast months only}

# Loop over different forecast horizon averages
n <- 4

lr_inf_infsq_fcmth <- lapply(1:n,function(x) lm_robust(netneg_fcmth ~ inf_f_x_dataframe_fcmth[,x]+inf_f_xsq_dataframe_fcmth[,x] + phillowe_fcmth, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_fcmth, summary)
print(lapply(lr_inf_infsq_fcmth, function(x) coef(summary(x))[,1:4]), digits = 2)
print(sapply(summaries, function(x) c(r_sq = x$r.squared, 
                                adj_r_sq = x$adj.r.squared)), digits = 3)
print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
print(lapply(lr_inf_infsq_fcmth, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 3)

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and a fixed effects for governor

#model_inf_01_fcmth <- lm(netneg_fcmth ~ inf_f_01_fcmth+inf_f_01sq_fcmth + phillowe_fcmth)
#lmtest::coeftest(model_inf_01_fcmth, vcov. = sandwich::vcovHC(model_inf_01_fcmth, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_01_est_fcmth <- -coef(model_inf_01_fcmth)[2]/(2*coef(model_inf_01_fcmth)[3])
#model_inf_01_est_fcmth


## Delta method standard error and CFI

#model_inf_01_est_se_fcmth <- deltamethod(~-x2/(2*x3),coef(model_inf_01_fcmth),vcovHC(model_inf_01_fcmth, type = 'HC1'))
#print(model_inf_01_est_se_fcmth)

#n <- 141
#error <- qt(0.975,df = n-1)*model_inf_01_est_se_fcmth /sqrt(n)
#print(error)
#left_cfi <- model_inf_01_est - error
#right_cfi <- model_inf_01_est + error
#print(left_cfi)
#print(right_cfi)
```

```{r Regression with inflation and output growth}

#Looping over different forecast horizon averages
n <- 6

lr_inf_infsq_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + gdp_f_x_dataframe[,x] + gdp_f_xsq_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_gdp_gdpsq, summary)
print(lapply(lr_inf_infsq_gdp_gdpsq, function(x) coef(summary(x))[,1:4]), digits = 3)
print(sapply(summaries, function(x) c(r_sq = x$r.squared, 
                                adj_r_sq = x$adj.r.squared)), digits = 3)
print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
print(lapply(lr_inf_infsq_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 5)

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and output growth average of 0-1 quarter ahead forecast, and a fixed effects for governor

#model_inf_gdp_01 <- lm(netneg ~ inf_f_01+inf_f_01sq +gdp_f_01+gdp_f_01sq + phillowe)
#lmtest::coeftest(model_inf_gdp_01, vcov. = sandwich::vcovHC(model_inf_gdp_01, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_gdp_01_est <- -coef(model_inf_gdp_01)[2]/(2*coef(model_inf_gdp_01)[3])
#model_inf_gdp_01_est

## Delta method standard error

#model_inf_gdp_01_est_se <- deltamethod(~-x2/(2*x3),coef(model_inf_gdp_01),vcovHC(model_inf_gdp_01, type = 'HC1'))
#print(model_inf_gdp_01_est_se)
```

```{r Regression with inflation and output growth - Forecast months only}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_gdp_gdpsq_fcmth <- lapply(1:n,function(x) lm_robust(netneg_fcmth ~ inf_f_x_dataframe_fcmth[,x]+inf_f_xsq_dataframe_fcmth[,x] + gdp_f_x_dataframe_fcmth[,x]+gdp_f_xsq_dataframe_fcmth[,x] + phillowe_fcmth, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_gdp_gdpsq_fcmth, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_gdp_gdpsq_fcmth, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and output growth average of 0-1 quarter ahead forecast, and a fixed effects for governor

#model_inf_gdp_01_fcmth <- lm(netneg_fcmth ~ inf_f_01_fcmth+inf_f_01sq_fcmth +gdp_f_01_fcmth+gdp_f_01sq_fcmth + phillowe_fcmth)
#lmtest::coeftest(model_inf_gdp_01_fcmth, vcov. = sandwich::vcovHC(model_inf_gdp_01_fcmth, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_gdp_01_est_fcmth <- -coef(model_inf_gdp_01_fcmth)[2]/(2*coef(model_inf_gdp_01_fcmth)[3])
#model_inf_gdp_01_est_fcmth

## Delta method standard error

#model_inf_gdp_01_est_se_fcmth <- deltamethod(~-x2/(2*x3),coef(model_inf_gdp_01_fcmth),vcovHC(model_inf_gdp_01_fcmth, type = 'HC1'))
#print(model_inf_gdp_01_est_se_fcmth)
```

```{r Regression with inflation and unemployment}

#Looping over different forecast horizon averages
n <- 6

lr_inf_infsq_ur_ursq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] +ur_f_x_dataframe[,x] + ur_f_xsq_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_ursq, summary)
print(lapply(lr_inf_infsq_ur_ursq, function(x) coef(summary(x))[,1:4]), digits = 3)
print(sapply(summaries, function(x) c(r_sq = x$r.squared, 
                                adj_r_sq = x$adj.r.squared)), digits = 3)
print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
print(lapply(lr_inf_infsq_ur_ursq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 5)

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and unemployment rate, and a fixed effects for governor

model_inf_ur_02 <- lm(netneg ~ inf_f_02+I(inf_f_02^2) +ur_f_02+I(ur_f_02^2) + phillowe)
#lmtest::coeftest(model_inf_ur_01, vcov. = sandwich::vcovHC(model_inf_ur_01, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_ur_01_est <- -coef(model_inf_ur_01)[2]/(2*coef(model_inf_ur_01)[3])
#model_inf_ur_01_est

## Delta method standard error

#model_inf_ur_01_est_se <- deltamethod(~-x2/(2*x3),coef(model_inf_ur_01),vcovHC(model_inf_ur_01, type = 'HC1'))
#print(model_inf_ur_01_est_se)

## Estimate for NAIRU

#model_inf_ur_01_est_NAIRU <- -coef(model_inf_ur_01)[4]/(2*coef(model_inf_ur_01)[5])
#print(model_inf_ur_01_est_NAIRU)

## Delta method standard error

#model_inf_ur_01_est_NAIRU_se <- deltamethod(~-x4/(2*x5),coef(model_inf_ur_01),vcov(model_inf_ur_01))
#print(model_inf_ur_01_est_NAIRU_se)
```

```{r Regression with inflation and unemployment - Forecast months only}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_ursq_fcmth <- lapply(1:n,function(x) lm_robust(netneg_fcmth ~ inf_f_x_dataframe_fcmth[,x]+inf_f_xsq_dataframe_fcmth[,x] +ur_f_x_dataframe_fcmth[,x]+ur_f_xsq_dataframe_fcmth[,x] + phillowe_fcmth, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_ursq_fcmth, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_ursq_fcmth, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))
lapply(summaries, function(x) -x$coef[4]/(2*x$coef[5]))
lapply(lr_inf_infsq_ur_ursq_fcmth, function(x) deltamethod(~-x4/(2*x5),x$coef, x$vcov))

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and unemployment rate, and a fixed effects for governor

#model_inf_ur_01_fcmth <- lm(netneg_fcmth ~ inf_f_01_fcmth+inf_f_01sq_fcmth +ur_f_01_fcmth+ur_f_01sq_fcmth + phillowe_fcmth)
#lmtest::coeftest(model_inf_ur_01_fcmth, vcov. = sandwich::vcovHC(model_inf_ur_01_fcmth, type = 'HC1'))

## The estimate for the inflation target

#model_inf_ur_01_est_fcmth <- -coef(model_inf_ur_01_fcmth)[2]/(2*coef(model_inf_ur_01_fcmth)[3])
#model_inf_ur_01_est_fcmth

## Delta method standard error

#model_inf_ur_01_est_se_fcmth <- deltamethod(~-x2/(2*x3),coef(model_inf_ur_01_fcmth),vcovHC(model_inf_ur_01_fcmth, type = 'HC1'))
#print(model_inf_ur_01_est_se_fcmth)

## Estimate for NAIRU

#model_inf_ur_01_est_NAIRU_fcmth <- -coef(model_inf_ur_01_fcmth)[4]/(2*coef(model_inf_ur_01_fcmth)[5])
#print(model_inf_ur_01_est_NAIRU_fcmth)

## Delta method standard error

#model_inf_ur_01_est_NAIRU_se_fcmth <- deltamethod(~-x4/(2*x5),coef(model_inf_ur_01_fcmth),vcov(model_inf_ur_01_fcmth))
#print(model_inf_ur_01_est_NAIRU_se_fcmth)
```

```{r Regression with inflation and unemployment and GDP}

#Looping over different forecast horizon averages
n <- 6

lr_inf_infsq_ur_ursq_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xsq_dataframe[,x] + gdp_f_x_dataframe[,x] + gdp_f_xsq_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq, summary)
print(lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq, function(x) coef(summary(x))[,1:4]), digits = 4)
print(sapply(summaries, function(x) c(r_sq = x$r.squared, 
                                adj_r_sq = x$adj.r.squared)), digits = 3)
print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
print(lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 5)

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and output growth and unemployment rate, and a fixed effects for governor

#model_inf_gdp_ur_01 <- lm(netneg ~ inf_f_01+inf_f_01sq +gdp_f_01 + gdp_f_01sq + ur_f_01 + ur_f_01sq+ phillowe)
#lmtest::coeftest(model_inf_gdp_ur_01, vcov. = sandwich::vcovHC(model_inf_gdp_ur_01, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_gdp_ur_01_est <- -coef(model_inf_gdp_ur_01)[2]/(2*coef(model_inf_gdp_ur_01)[3])
#model_inf_gdp_ur_01_est

## Delta method standard error

#model_inf_gdp_ur_01_est_se <- deltamethod(~-x2/(2*x3),coef(model_inf_gdp_ur_01),vcovHC(model_inf_gdp_ur_01, type = 'HC1'))
#print(model_inf_gdp_ur_01_est_se)
```

```{r Regression with inflation and unemployment and GDP - Forecast months only}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_ursq_gdp_gdpsq_fcmth <- lapply(1:n,function(x) lm_robust(netneg_fcmth ~ inf_f_x_dataframe_fcmth[,x]+inf_f_xsq_dataframe_fcmth[,x] + ur_f_x_dataframe_fcmth[,x] + ur_f_xsq_dataframe_fcmth[,x] + gdp_f_x_dataframe_fcmth[,x] + gdp_f_xsq_dataframe_fcmth[,x] + phillowe_fcmth, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq_fcmth, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq_fcmth, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))
lapply(summaries, function(x) -x$coef[4]/(2*x$coef[5]))
lapply(lr_inf_infsq_ur_ursq_gdp_gdpsq_fcmth, function(x) deltamethod(~-x4/(2*x5),x$coef, x$vcov))

## Linear regression model with average of 0-1 quarter ahead inflation, and its squared term, and output growth and unemployment rate, and a fixed effects for governor

#model_inf_gdp_ur_01_fcmth <- lm(netneg_fcmth ~ inf_f_01_fcmth+inf_f_01sq_fcmth +gdp_f_01_fcmth+ gdp_f_01sq_fcmth+ ur_f_01_fcmth + ur_f_01sq_fcmth + phillowe_fcmth)
#lmtest::coeftest(model_inf_gdp_ur_01_fcmth, vcov. = sandwich::vcovHC(model_inf_gdp_ur_01_fcmth, type = 'HC1'))
#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_gdp_ur_01_est_fcmth <- -coef(model_inf_gdp_ur_01_fcmth)[2]/(2*coef(model_inf_gdp_ur_01_fcmth)[3])
#model_inf_gdp_ur_01_est_fcmth

## Delta method standard error

#model_inf_gdp_ur_01_est_se_fcmth <- deltamethod(~-x2/(2*x3),coef(model_inf_gdp_ur_01_fcmth),vcovHC(model_inf_gdp_ur_01_fcmth, type = 'HC1'))
#print(model_inf_gdp_ur_01_est_se_fcmth)
```

```{r Regression with inflation and unemployment and GDP, linear unemployment}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + gdp_f_x_dataframe[,x] + gdp_f_xsq_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_gdpsq, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))
```

```{r Regression with inflation and unemployment and GDP, linear unemployment and linear GDP growth}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + gdp_f_x_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_gdpsq, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))
```

```{r Regression with inflation and unemployment and GDP, linear GDP growth}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xsq_dataframe[,x] + gdp_f_x_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_gdpsq, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))

```

```{r Regression with inflation and unemployment and GDP, linear unemployment and interaction term for increasing path of forecasts, and linear GDP growth}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_gdpsq <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xinc_dataframe[,x] + gdp_f_x_dataframe[,x] + phillowe, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_gdpsq, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_gdpsq, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))
```

```{r Regression with inflation and squared term, unemployment, GDP, Australian uncertainty and us_ffr, linear GDP growth}

#Looping over different forecast horizon averages
#n <- 4

#\lr_inf_infsq_ur_gdp_uncertainty_usffr <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x]  + gdp_f_x_dataframe[,x]+ phillowe + uncertainty + us_ffr, se_type = 'stata'))
#lr_inf_infsq_ur_gdp_uncertainty_usffr <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xsq_dataframe[,x] + gdp_f_x_dataframe[,x]+ phillowe + uncertainty + us_ffr, se_type = 'stata'))
#lr_inf_infsq_ur_gdp_uncertainty_usffr <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xinc_dataframe[,x] + gdp_f_x_dataframe[,x]+ phillowe + uncertainty + us_ffr, se_type = 'stata'))

#summaries <- lapply(lr_inf_infsq_ur_gdp_uncertainty_usffr, summary)
#print(lapply(lr_inf_infsq_ur_gdp_uncertainty_usffr, function(x) coef(summary(x))[,1:4]), digits = 4)
#print(sapply(summaries, function(x) c(r_sq = x$r.squared,                                 adj_r_sq = x$adj.r.squared)), digits = 3)
#print(lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3])), digits = 4)
#print(lapply(lr_inf_infsq_ur_gdp_uncertainty_usffr, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov)), digits = 5)

lr_uncertainty_usffr_ur <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + ntwiyeg +  commpi_inf_q4 + rppiqg + us_ffr +0, se_type = 'stata')

lr_uncertainty_usffr_ursq <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + ur_f_02sq + ntwiyeg+   commpi_inf_q4 + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_urinc <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + ur_f_02_inc  + ntwiyeg +   commpi_inf_q4  + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_ur_gdp <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + gdp_f_02 + ntwiyeg+   commpi_inf_q4 + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_ursq_gdp <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + ur_f_02sq  + gdp_f_02 + ntwiyeg +   commpi_inf_q4 + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_urinc_gdp <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + ur_f_02 + ur_f_02_inc + gdp_f_02  + ntwiyeg +   commpi_inf_q4  + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_gdp <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + gdp_f_02 + ntwiyeg +   commpi_inf_q4  + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_gdp_gdpsq <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + gdp_f_02 + gdp_f_02sq + ntwiyeg +   commpi_inf_q4 + rppiqg+ us_ffr+0, se_type = 'stata')

lr_uncertainty_usffr_gdp_gdpsq_ur <- lm_robust(netnegur ~ inf_f_02 +inf_f_02sq + gdp_f_02 + gdp_f_02sq + ur_f_02+ ntwiyeg +   commpi_inf_q4  + rppiqg+ us_ffr+0, se_type = 'stata')

#lr_uncertainty_usffr_ur
#lr_uncertainty_usffr_ursq
#lr_uncertainty_usffr_urinc
#lr_uncertainty_usffr_ur_gdp
#lr_uncertainty_usffr_ursq_gdp
#lr_uncertainty_usffr_urinc_gdp
texreg(list(lr_uncertainty_usffr_ur,lr_uncertainty_usffr_ursq, lr_uncertainty_usffr_urinc, lr_uncertainty_usffr_ur_gdp,lr_uncertainty_usffr_ursq_gdp, lr_uncertainty_usffr_urinc_gdp, lr_uncertainty_usffr_gdp, lr_uncertainty_usffr_gdp_gdpsq, lr_uncertainty_usffr_gdp_gdpsq_ur),  include.ci = FALSE, digits = 3, stars = c(0.01,0.05,0.1))

## The estimate for the inflation target

lr_uncertainty_usffr_ur_est <- -coef(lr_uncertainty_usffr_ur)[2]/(2*coef(lr_uncertainty_usffr_ur)[3])
lr_uncertainty_usffr_ur_est

## Delta method standard error

lr_uncertainty_usffr_ur_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_ur),lr_uncertainty_usffr_ur$vcov)
print(lr_uncertainty_usffr_ur_est_se)

## The estimate for the inflation target

lr_uncertainty_usffr_ursq_est <- -coef(lr_uncertainty_usffr_ursq)[2]/(2*coef(lr_uncertainty_usffr_ursq)[3])
lr_uncertainty_usffr_ursq_est

## Delta method standard error

lr_uncertainty_usffr_ursq_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_ursq),lr_uncertainty_usffr_ursq$vcov)
print(lr_uncertainty_usffr_ursq_est_se)

## The estimate for the inflation target

lr_uncertainty_usffr_urinc_est <- -coef(lr_uncertainty_usffr_urinc)[2]/(2*coef(lr_uncertainty_usffr_urinc)[3])
lr_uncertainty_usffr_urinc_est

## Delta method standard error

lr_uncertainty_usffr_urinc_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_urinc),lr_uncertainty_usffr_urinc$vcov)
print(lr_uncertainty_usffr_urinc_est_se)

## The estimate for the inflation target

lr_uncertainty_usffr_ur_gdp_est <- -coef(lr_uncertainty_usffr_ur_gdp)[2]/(2*coef(lr_uncertainty_usffr_ur_gdp)[3])
lr_uncertainty_usffr_ur_gdp_est

## Delta method standard error

lr_uncertainty_usffr_ur_gdp_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_ur_gdp),lr_uncertainty_usffr_ur_gdp$vcov)
print(lr_uncertainty_usffr_ur_gdp_est_se)

## The estimate for the inflation target

lr_uncertainty_usffr_ursq_gdp_est <- -coef(lr_uncertainty_usffr_ursq_gdp)[2]/(2*coef(lr_uncertainty_usffr_ursq_gdp)[3])
lr_uncertainty_usffr_ursq_gdp_est

## Delta method standard error

lr_uncertainty_usffr_ursq_gdp_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_ursq_gdp),lr_uncertainty_usffr_ursq_gdp$vcov)
print(lr_uncertainty_usffr_ursq_gdp_est_se)

## The estimate for the inflation target

lr_uncertainty_usffr_urinc_gdp_est <- -coef(lr_uncertainty_usffr_urinc_gdp)[2]/(2*coef(lr_uncertainty_usffr_urinc_gdp)[3])
lr_uncertainty_usffr_urinc_gdp_est

## Delta method standard error

lr_uncertainty_usffr_urinc_gdp_est_se <- deltamethod(~-x2/(2*x3),coef(lr_uncertainty_usffr_urinc_gdp),lr_uncertainty_usffr_urinc_gdp$vcov)
print(lr_uncertainty_usffr_urinc_gdp_est_se)
```

```{r Regression with inflation and squared term, unemployment, GDP and exchange rate}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_ntwi <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + gdp_f_x_dataframe[,x]+ phillowe + ntwiqg, se_type = 'stata'))
#lr_inf_infsq_ur_gdp_ntwi <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xsq_dataframe[,x] + gdp_f_x_dataframe[,x]+ phillowe + ntwiqg, se_type = 'stata'))
#lr_inf_infsq_ur_gdp_ntwi <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + ur_f_xinc_dataframe[,x] + gdp_f_x_dataframe[,x]+ phillowe + ntwiqg, se_type = 'stata'))
summaries <- lapply(lr_inf_infsq_ur_gdp_ntwi, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_ntwi, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))

#stargazer(model_inf_01,title = "Results",align = TRUE)

## The estimate for the inflation target

#model_inf_gdp_ur_01_est <- -coef(model_inf_gdp_ur_01)[2]/(2*coef(model_inf_gdp_ur_01)[3])
#model_inf_gdp_ur_01_est

## Delta method standard error

#model_inf_gdp_ur_01_est_se <- deltamethod(~-x2/(2*x3),coef(model_inf_gdp_ur_01),vcovHC(model_inf_gdp_ur_01, type = 'HC1'))
#print(model_inf_gdp_ur_01_est_se)
```

```{r Regression with inflation and squared term, unemployment, GDP and BBB corporate bond yield to 10 year AGS spread}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_ausbbb <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + phillowe + aus_bbb + uncertainty, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_ausbbb, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_ausbbb, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))

```

```{r Regression with inflation and squared term, unemployment, GDP and house prices}

#Looping over different forecast horizon averages
n <- 4

lr_inf_infsq_ur_gdp_ehpiyeg <- lapply(1:n,function(x) lm_robust(netneg ~ inf_f_x_dataframe[,x]+inf_f_xsq_dataframe[,x] + ur_f_x_dataframe[,x] + gdp_f_x_dataframe[,x] + ehpi + us_ffr + uncertainty + ntwi, se_type = 'stata'))

summaries <- lapply(lr_inf_infsq_ur_gdp_ehpiyeg, summary)
lapply(summaries, function(x) x$coefficients[, c(1,4)])
lapply(summaries, function(x) -x$coef[2]/(2*x$coef[3]))
lapply(lr_inf_infsq_ur_gdp_ehpiyeg, function(x) deltamethod(~-x2/(2*x3),x$coef, x$vcov))

```

```{r Graph}
visreg(model_inf_02, "inf_f_02",gg = 'True')
visreg(model_inf_ur_02, "ur_f_02", gg = 'True')
```

```{r Testing house price coefficient time varying}
model_inf_rppi_02 <- lm_robust(netneg ~ inf_f_02+ I(inf_f_02^2) + rppiyeg + I(rppiyeg * post_2012) + phillowe, se_type = 'stata')
summary(model_inf_rppi_02)
```

```{r Time varying inflation target}
alpha_0_gridsearch <- seq(0,4,by=0.01)
alpha_1_gridsearch <- seq(-1,1,by=0.001)
data$obs <- as.numeric(rownames(data)) 
dat <- data.frame()
data <- filter(data, Dates <= as.Date("2019/06/04"))

for (date in data$Dates)
  {
  s = date
  s_num <- which(data$Dates == s)
  data_subset = filter(data, Dates > s)
  alpha_0_optimisation <- list("target_optimal" =    0,"rsquared_optimal" = 0)
  
if (s!= as.Date("2019/06/04"))
{  for (alpha_0 in alpha_0_gridsearch)
  {
    model_alpha_0 <- lm(data_subset$`Net negativity score` ~ I(abs((data_subset$fccpiiq0+ data_subset$fccpiiq1 + data_subset$fccpiiq2)/3 - alpha_0)) + data_subset$`Phillip Lowe`)

    if (summary(model_alpha_0)$r.squared > alpha_0_optimisation$rsquared_optimal )
    {
      alpha_0_optimisation$rsquared_optimal <- summary(model_alpha_0)$r.squared
      alpha_0_optimisation$target_optimal <- alpha_0
    }
data_frame_alpha_0 <- data.frame(s_num, s, alpha_0_optimisation$target_optimal)
}

alpha_1_optimisation <- list("alpha_1_optimal" =    -1,"rsquared_optimal" = 0)
    
alpha_0 <- data_frame_alpha_0$alpha_0_optimisation.target_optimal
for (alpha_1 in alpha_1_gridsearch) 
  {
  model_alpha_1 <- lm(data_subset$`Net negativity score` ~ I(abs((data_subset$fccpiiq0+ data_subset$fccpiiq1 + data_subset$fccpiiq2)/3 - (alpha_0+alpha_1*(s_num - data_subset$obs)))) + data_subset$`Phillip Lowe`)
  if (summary(model_alpha_1)$r.squared > alpha_1_optimisation$rsquared_optimal)
  {
    alpha_1_optimisation$rsquared_optimal <- summary(model_alpha_1)$r.squared
      alpha_1_optimisation$alpha_1_optimal <- alpha_1
  }
  data_frame_alpha_1 <- data.frame(alpha_1_optimisation$alpha_1_optimal)
}

alpha_1 <- data_frame_alpha_1$alpha_1_optimisation.alpha_1_optimal
alpha_1_gridsearch = seq (-9*alpha_1, 11*alpha_1, by= (20*alpha_1/100))
alpha_2_gridsearch = seq(-0.0001,0.0001, by = 0.00001)

alpha_12_optimisation <- list("alpha_1_optimal" =   0, "alpha_2_optimal" = 0,"rsquared_optimal" = 0)

for (alpha_1 in alpha_1_gridsearch)
{
  for (alpha_2 in alpha_2_gridsearch)
  {
    model_alpha_12<- lm(data_subset$`Net negativity score` ~ I(abs((data_subset$fccpiiq0+ data_subset$fccpiiq1 + data_subset$fccpiiq2)/3 - (alpha_0+alpha_1*(s_num - data_subset$obs) + alpha_2*(s_num - data_subset$obs)^2))) + data_subset$`Phillip Lowe`)
    if (summary(model_alpha_12)$r.squared > alpha_12_optimisation$rsquared_optimal)
  {
    alpha_12_optimisation$rsquared_optimal <- summary(model_alpha_12)$r.squared
      alpha_12_optimisation$alpha_1_optimal <- alpha_1
      alpha_12_optimisation$alpha_2_optimal <- alpha_2
  }
  data_frame_alpha_12 <- data.frame(alpha_12_optimisation$alpha_1_optimal, alpha_12_optimisation$alpha_2_optimal)
  data_frame <- merge(data_frame_alpha_0, data_frame_alpha_1)
  data_frame <- merge(data_frame, data_frame_alpha_12)
}
  }
  
}
dat <- rbind(dat, data_frame)
}
```


